### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by marcoponzi** [cvocp/cvocp#1]
I have this error when running ocpcluster.py on Ubuntu, with pydot.1.2.4

Apparently, the problem is that Python uses 'ascii' as default encoding. I was able to apply a quick and dirty work-around to the problem by adding these lines at  ocpcluster.py line 16:
```
reload(sys)  # Reload does the trick!
sys.setdefaultencoding('UTF8')
```
as suggested here:
https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

I must say I am very ignorant of python, so I am probably missing something trivial. BTW, I love what I have seen of your work so far!

Here is the complete traceback:

Traceback (most recent call last):
  File "ocpcluster.py", line 139, in <module>
    graph.write_pdf("example1_graph.pdf")
  File "/usr/local/lib/python2.7/dist-packages/pydot.py", line 1673, in new_method
    encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/pydot.py", line 1836, in create
    self.write(tmp_name, encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/pydot.py", line 1752, in write
    s = unicode(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12: ordinal not in range(128)

**Comment by manexagirrezabal** [comment]
I was testing the program and I think I found out why this is not working. It looks like the pydot package doesn't like UTF8 encoded strings. Then, if you just comment the lines no. 127, 130 and 135, the program will run and it will plot the graph. It should look like this:

```for k in ls.tree:
    s0 = u"\u00a0".join(sorted(list(ls.tree[k])))
#    s0 = s0.encode('utf-8')    
    if k + '0' in ls.tree:
        s00 = u"\u00a0".join(sorted(list(ls.tree[k + '0'])))
#        s00 = s00.encode('utf-8')
        edge = pydot.Edge(s0,s00)
        graph.add_edge(edge)
    if k + '1' in ls.tree:
        s01 = u"\u00a0".join(sorted(list(ls.tree[k + '1'])))
 #       s01 = s01.encode('utf-8')
        edge = pydot.Edge(s0,s01)
        graph.add_edge(edge)

graph.write_pdf("example1_graph.pdf")
os.system("open example1_graph.pdf")```
